function ms_disp_or_slice
% function ms_disp_or_slice;
% draw menu options for display or slice (conventional or PSD detectors) for single crystal samples


% === if Control Window non-existent, return
fig=findobj('Tag','ms_ControlWindow');
if isempty(fig),
   disp('Control Window non-existent. Return.')
   return;
end

 % get gui and clear powder menu if present;
mslice_gui = msui_collection(fig,'mslice_gui');
delete(mslice_gui,{'powder_axis','powder_slice','powder_cut','delta_phi_range','powder_rebin_step','cut_output'});

% === if no analysis mode defined , return
analobj=findobj(fig,'Tag','ms_analysis_mode');
if isempty(analobj),
   disp('No analysis mode selected. Return.')
   return;
end

% === if Detector Type not defined, return
det_type_obj=findobj(fig,'Tag','ms_det_type');
if isempty(det_type_obj),
   disp('No detector type selected. Return.')
   return;
end
   
% === get position parameters for items displayed on the Control Window
pos=get(findobj(fig,'String','AnalysisMode'),'Position');
lineheight=pos(4);
pos1=get(analobj,'Position');
interlines=pos1(4)-lineheight;
white=get(analobj,'BackgroundColor');
%
oneline=[0 lineheight 0 0];

psd=(get(det_type_obj,'Value')==1); % =1 (PSD) =0 (conventional, non-PSD detectors)


global coltab;
if isempty(coltab)
    load coltab.dat -ascii;
end
if psd
    pos = ui_cryst_analysis_psd(fig,pos,oneline,interlines,white,coltab);
else
    pos = ui_cryst_analysis_nonpsd(fig,pos,oneline,interlines,white,coltab);
end


%========= OutputFile + To Mfit pushbutton + Generate bkg(E) button ==================
%pos=pos-oneline;
msui_cut_output(fig,pos,oneline,interlines,white,1);
%



function pos=ui_cryst_analysis_psd(fig,pos,oneline,interlines,white,coltab)
this_name = 'cryst_analysis_psd';

% === update menu option for detector trajectories
strings={'Q_x','Q_y','Q_z','H','K','L','u1','u2','u3','Energy','|Q|','2Theta','Azimuth','Det Group Number'};

set(findobj(fig,'Tag','ms_plot_traj_x'),'Value',2,'String',strings);
set(findobj(fig,'Tag','ms_plot_traj_y'),'Value',1,'String',strings);
strings{length(strings)+1}='none';
set(findobj(fig,'Tag','ms_plot_traj_z'),'String',strings,'Value',length(strings));
drawnow;

mslice_gui = msui_collection(fig,'mslice_gui');
mslice_gui = delete(mslice_gui,'cryst_analysis_nonpsd');
if exist(mslice_gui,this_name)
    pos = get_line_pos(get(mslice_gui,this_name));
    return
end
width = pos(3);

%========= Orthogonal Viewing Axes ==================
pos=pos-1.5*oneline;
h{1}=uicontrol('Parent',fig,'Style','text','String','Orthogonal',...
   'Position',pos+[0 0 0*width 0],'BackgroundColor',white,'Visible','off');
pos=pos-oneline;
h{2}=uicontrol('Parent',fig,'Style','text','String','Viewing Axes',...
   'Position',pos+[0 0 0*width 0],'BackgroundColor',white,'Visible','off');

%========= a* b* c* E ==================
%pos=pos-oneline;
h{3}=uicontrol('Parent',fig,'Style','text','String','a*',...
	'HorizontalAlignment','center',...
   'Position',pos+[width 0 -width*1/3 0],'Visible','off');
h{4}=uicontrol('Parent',fig,'Style','text','String','b*',...
	'HorizontalAlignment','center',...
   'Position',pos+[2*width 0 -width*1/3 0],'Visible','off');
h{5}=uicontrol('Parent',fig,'Style','text','String','c*',...
	'HorizontalAlignment','center',...
   'Position',pos+[3*width 0 -width*1/3 0],'Visible','off');
h{6}=uicontrol('Parent',fig,'Style','text','String','Energy',...
	'HorizontalAlignment','center',...
   'Position',pos+[4*width 0 -width*1/3 0],'Visible','off');
h{7}=uicontrol('Parent',fig,'Style','text','String','Label',...
	'HorizontalAlignment','center',...
   'Position',pos+[5*width 0 0 0],'Visible','off');

%========= u1  ==================
pos=pos-oneline;
h{8}=uicontrol('Parent',fig,'Style','text','String','u1',...
   'Position',pos,'Visible','off');
h{9}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u11',...
   'Position',pos+[width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{10}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u12',...
   'Position',pos+[2*width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{11}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u13',...
   'Position',pos+[3*width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{12}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u14',...
   'Position',pos+[4*width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{13}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u1label',...
   'Position',pos+[5*width 0 0 interlines],...
   'HorizontalAlignment','left','Callback','ms_updatelabel(1)',...
   'BackgroundColor',white,'Visible','off');

%========= u2  ==================
pos=pos-oneline;
h{14}=uicontrol('Parent',fig,'Style','text','String','u2',...
   'Position',pos,'Visible','off');
h{15}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u21',...
   'Position',pos+[width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{16}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u22',...
   'Position',pos+[2*width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{17}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u23',...
   'Position',pos+[3*width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{18}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u24',...
   'Position',pos+[4*width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{19}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u2label',...
   'Position',pos+[5*width 0 0 interlines],...
   'HorizontalAlignment','left','Callback','ms_updatelabel(2)',...
   'BackgroundColor',white,'Visible','off');

%========= u3  ==================
pos=pos-oneline;
h{20}=uicontrol('Parent',fig,'Style','text','String','u3',...
   	'Position',pos,'Visible','off');
h{21}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u31',...
   	'Position',pos+[width 0 -width*1/3 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{22}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u32',...
  	 	'Position',pos+[2*width 0 -width*1/3 interlines],...
  	 	'HorizontalAlignment','left',...
  	 	'BackgroundColor',white,'Visible','off');
h{23}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u33',...
   	'Position',pos+[3*width 0 -width*1/3 interlines],...
	   'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{24}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u34',...
  	 	'Position',pos+[4*width 0 -width*1/3 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{25}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u3label',...
   	'Position',pos+[5*width 0 0 interlines],...
   	'HorizontalAlignment','left','Callback','ms_updatelabel(3)',...
   	'BackgroundColor',white,'Visible','off');

%========= Calculate Projections ==================
%pos=pos-oneline;
h{26}=uicontrol('Parent',fig,'Style','pushbutton','String','Calculate Projections',...
   'Callback','ms_calc_proj;',...
   'Position',pos+[6*width 0 width 0],'Visible','off'); 

%========= Slice plane/Display  ==================
pos=pos-1.5*oneline;
h{27}=uicontrol('Parent',fig,'Style','text','String','Slice plane',...
      'Position',pos,'BackgroundColor',white,'Tag','ms_slice_data','Visible','off');
% === After each plot/surf slice, the slice_data will be stored in 'UserData' field of above object

%========= Slice plane, vz_min, vz_max ==================
   pos=pos-oneline;
h{28}=uicontrol('Parent',fig,'Style','text','String','perp to axis',...
   	'Position',pos,'Visible','off');
h{29}=uicontrol('Parent',fig,'Style','popupmenu','String',{'u1','u2','u3'},...
	   'Tag','ms_slice_z',...
  	 	'Position',pos+[width 0 width*1/4 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,...
   	'Callback','ms_slice_axes;','Visible','off');
h{30}=uicontrol('Parent',fig,'Style','text','String','thickness ',...
  		'Position',pos+[2*width+width*1/4 0 -width*1/4 0],'Visible','off');
h{31}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_slice_vz_min',...
   	'Position',pos+[3*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{32}=uicontrol('Parent',fig,'Style','text','String','to',...
  		'Position',pos+[4*width 0 0 0],'Visible','off');
h{33}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_slice_vz_max',...
   	'Position',pos+[5*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
      'BackgroundColor',white,'Visible','off');


%========= Slice/Display vx_min, vx_max, bin_vx ==================
pos=pos-oneline;

h{34}=uicontrol('Parent',fig,'Style','text','String','horizontal range ',...
		'Tag','ms_slice_x_axis',...
   	'Position',pos+[width 0 width 0],'Visible','off');
h{35}=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_vx_min',...
  	 	'Position',pos+[3*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{36}=uicontrol('Parent',fig,'Style','text','String','to',...
   	'Position',pos+[4*width 0 0 0],'Visible','off');
h{37}=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_vx_max',...
   	'Position',pos+[5*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{38}=uicontrol('Parent',fig,'Style','text','String','step',...
   	'Position',pos+[6*width 0 0 0],'Visible','off');
h{39}=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_bin_vx',...
   	'Position',pos+[7*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');

%========= Slice/Display vy_min, vy_max, bin_vy ==================
pos=pos-oneline;

h{40}=uicontrol('Parent',fig,'Style','text','String','vertical range',...
  		'Tag','ms_slice_y_axis',...
   	'Position',pos+[width 0 width 0],'Visible','off');
h{41}=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_vy_min',...
   	'Position',pos+[3*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{42}=uicontrol('Parent',fig,'Style','text','String','to',...
   	'Position',pos+[4*width 0 0 0],'Visible','off');
h{43}=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_vy_max',...
   	'Position',pos+[5*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{44}=uicontrol('Parent',fig,'Style','text','String','step',...
   	'Position',pos+[6*width 0 0 0],'Visible','off');
h{45}=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_bin_vy',...
   	'Position',pos+[7*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
%========= Slice/Display Intensity range ==================
pos=pos-oneline;

h{46}=uicontrol('Parent',fig,'Style','text','String','Intensity range*',...
   	'Position',pos+[width 0 width 0],'Visible','off');
h{47}=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_i_min',...
   	'Position',pos+[3*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{48}=uicontrol('Parent',fig,'Style','text','String','to *',...
   	'Position',pos+[4*width 0 0 0],'Visible','off');
h{49}=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_i_max',...
   	'Position',pos+[5*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{50}=uicontrol('Parent',fig,'Style','text','String','Colour map',...
   	'Position',pos+[6*width 0 0 0],'Visible','off');
% clotab
h{51}=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_slice_colmap',...
   	'Position',pos+[7*width -interlines 0 interlines],...
   	'HorizontalAlignment','left',...
   	'String',{'black->red','log10(blk-red)','blue->red'},...
   	'BackgroundColor',white,'Value',1,'UserData',coltab,'Visible','off');
   
%========= Slice/Display Smooth Level and Shading ==================
pos=pos-oneline;
h{52}=uicontrol('Parent',fig,'Style','text','String','Smoothing level*',...
   'Position',pos+[width 0 width 0],'Visible','off');

h{53}=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_nsmooth',...
   	'Position',pos+[3*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{54}=uicontrol('Parent',fig,'Style','text','String','Shading',...
   	'Position',pos+[4*width 0 0 0],'Visible','off');
h{55}=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_slice_shad',...
   	'Position',pos+[5*width -interlines 0 interlines],...
   	'HorizontalAlignment','left',...
   	'String',{'flat','faceted','interp'},...
      'BackgroundColor',white,'Value',1,'Visible','off');


%========= Do Slice and Do Surf Slice / Do Display ==================
%pos=pos-oneline;

h{56}=uicontrol('Parent',fig,'Style','pushbutton','String','Plot Slice',...
   	'Callback','ms_slice;',...
   	'Position',pos+[6*width 0 0 0],'Visible','off'); 
h{57}=uicontrol('Parent',fig,'Style','pushbutton','String','Surf Slice',...
   	'Callback','ms_slice(''surf'');',...
      'Position',pos+[7*width 0 0 0],'Visible','off');

%========= Cut  ==================
pos=pos-1.5*oneline;
h{58}=uicontrol('Parent',fig,'Style','text','String','Cut',...
   'Position',pos,'BackgroundColor',white,'Visible','off');

%========= Cut axis, vx_min, vx_max ==================
pos=pos-oneline;
h{59}=uicontrol('Parent',fig,'Style','text','String',' along axis ',...
   'Position',pos,'Visible','off');

h{60}=uicontrol('Parent',fig,'Style','popupmenu','String',{'u1','u2','u3'},...
	   'Tag','ms_cut_x',...
  		'Position',pos+[width 0 width*1/4 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,...
      'Callback','ms_cut_axes;','Visible','off');

h{61}=uicontrol('Parent',fig,'Style','text','String','from',...
   'Position',pos+[2*width+width*1/4 0 -width*1/4 0],'Visible','off');
h{62}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_cut_vx_min',...
   'Position',pos+[3*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{63}=uicontrol('Parent',fig,'Style','text','String','to',...
   'Position',pos+[4*width 0 0 0],'Visible','off');
h{64}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_cut_vx_max',...
   'Position',pos+[5*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{65}=uicontrol('Parent',fig,'Style','text','String','step',...
   'Position',pos+[6*width 0 0 0],'Visible','off');
h{66}=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_bin_vx',...
   'Position',pos+[7*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');

%========= Cut vy_min, vy_max ==================
pos=pos-oneline;
h{67}=uicontrol('Parent',fig,'Style','text','String','thickness range',...
	'Tag','ms_cut_y_axis',...
   'Position',pos+[width 0 width 0],'Visible','off');
h{68}=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_vy_min',...
   'Position',pos+[3*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{69}=uicontrol('Parent',fig,'Style','text','String','to',...
   'Position',pos+[4*width 0 0 0],'Visible','off');
h{70}=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_vy_max',...
   'Position',pos+[5*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');

%========= Cut vz_min, vz_max ==================
	pos=pos-oneline;
 h{71}=uicontrol('Parent',fig,'Style','text','String','thickness range',...
		'Tag','ms_cut_z_axis',...
   	'Position',pos+[width 0 width 0],'Visible','off');
h{72}=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_vz_min',...
   	'Position',pos+[3*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{73}=uicontrol('Parent',fig,'Style','text','String','to',...
   	'Position',pos+[4*width 0 0 0],'Visible','off');
h{74}=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_vz_max',...
   	'Position',pos+[5*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
      'BackgroundColor',white,'Visible','off');


h{75}=uicontrol('Parent',fig,'Style','text','String','Symbol',...
  	'Position',pos+[6*width 0 0 0],'Visible','off');
h{76}=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_symbol_colour',...
  	'Position',pos+[7*width 0 0 interlines],...
  	'String',{'white','red','blue','magenta','green','cyan','yellow','black'},...
  	'BackgroundColor',white,'Visible','off');

%========= Cut Intensity range and Data Symbol ==================
pos=pos-oneline;
strings={'Intensity','Q_x','Q_y','Q_z','H','K','L','u1','u2','u3','Energy','|Q|','2Theta','Azimuth','Det Group Number'};

h{77}=uicontrol('Parent',fig,'Style','popupmenu','String',strings,...
   'Value',1,'BackgroundColor',white,'Tag','ms_cut_intensity',...
   'Position',pos+[width 0 width*1/4 interlines],'Visible','off');
h{78}=uicontrol('Parent',fig,'Style','text','String','range*',...
   'Position',pos+[(2+1/4)*width 0 -width*1/4 0],'Visible','off');
h{79}=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_i_min',...
   'Position',pos+[3*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{80}=uicontrol('Parent',fig,'Style','text','String','to *',...
   'Position',pos+[4*width 0 0 0],'Visible','off');
h{81}=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_i_max',...
   'Position',pos+[5*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{82}=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_symbol_type',...
   'Position',pos+[6*width 0 0 interlines],...
   'String',{'circle o','square','diamond','pentagram','hexagram','star *','cross x','plus +',...
   'triangle u','triangle d','triangle r','triangle l','point .'},...
	'BackgroundColor',white,'Visible','off');
h{83}=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_symbol_line',...
   'Position',pos+[7*width 0 0 interlines],...
   'String',{'no line','solid -','dashed --','dotted ..','dash-dot _.'},...
   'BackgroundColor',white,'Visible','off');

det_psd_cut= graph_objects_collection(this_name); 
add(mslice_gui,add_handles(det_psd_cut,h));  


function pos=ui_cryst_analysis_nonpsd(fig,pos,oneline,interlines,white,coltab)
this_name='cryst_analysis_nonpsd'; 
% === update menu option for detector trajectories

strings={'Q_x','Q_y','Q_z','H','K','L','u1','u2','Energy','|Q|','2Theta','Azimuth','Det Group Number'};

set(findobj(fig,'Tag','ms_plot_traj_x'),'Value',2,'String',strings);
set(findobj(fig,'Tag','ms_plot_traj_y'),'Value',1,'String',strings);
strings{length(strings)+1}='none';
set(findobj(fig,'Tag','ms_plot_traj_z'),'String',strings,'Value',length(strings));
drawnow;

mslice_gui = msui_collection(fig,'mslice_gui');
mslice_gui = delete(mslice_gui,'cryst_analysis_psd');
if exist(mslice_gui,this_name)
    pos = get_line_pos(get(mslice_gui,this_name));
    return
end
width = pos(3);

%========= Orthogonal Viewing Axes ==================
pos=pos-1.5*oneline;
h{1}=uicontrol('Parent',fig,'Style','text','String','Orthogonal',...
   'Position',pos+[0 0 0*width 0],'BackgroundColor',white,'Visible','off');
pos=pos-oneline;
h{2}=uicontrol('Parent',fig,'Style','text','String','Viewing Axes',...
   'Position',pos+[0 0 0*width 0],'BackgroundColor',white,'Visible','off');

%========= a* b* c* E ==================
%pos=pos-oneline;
h{3}=uicontrol('Parent',fig,'Style','text','String','a*',...
	'HorizontalAlignment','center',...
   'Position',pos+[width 0 -width*1/3 0],'Visible','off');
h{4}=uicontrol('Parent',fig,'Style','text','String','b*',...
    	'HorizontalAlignment','center',...
   'Position',pos+[2*width 0 -width*1/3 0],'Visible','off');
h{5}=uicontrol('Parent',fig,'Style','text','String','c*',...
	'HorizontalAlignment','center',...
   'Position',pos+[3*width 0 -width*1/3 0],'Visible','off');
h{6}=uicontrol('Parent',fig,'Style','text','String','Energy',...
	'HorizontalAlignment','center',...
   'Position',pos+[4*width 0 -width*1/3 0],'Visible','off');
h{7}=uicontrol('Parent',fig,'Style','text','String','Label',...
    	'HorizontalAlignment','center',...
        'Position',pos+[5*width 0 0 0],'Visible','off');

%========= u1  ==================
pos=pos-oneline;
h{8}=uicontrol('Parent',fig,'Style','text','String','u1',...
   'Position',pos,'Visible','off');
h{9}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u11',...
   'Position',pos+[width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{10}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u12',...
   'Position',pos+[2*width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{11}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u13',...
   'Position',pos+[3*width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{12}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u14',...
   'Position',pos+[4*width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{13}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u1label',...
   'Position',pos+[5*width 0 0 interlines],...
   'HorizontalAlignment','left','Callback','ms_updatelabel(1)',...
   'BackgroundColor',white,'Visible','off');

%========= u2  ==================
pos=pos-oneline;
h{14}=uicontrol('Parent',fig,'Style','text','String','u2',...
   'Position',pos,'Visible','off');
h{15}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u21',...
   'Position',pos+[width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{16}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u22',...
   'Position',pos+[2*width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{17}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u23',...
   'Position',pos+[3*width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{18}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u24',...
   'Position',pos+[4*width 0 -width*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{19}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u2label',...
   'Position',pos+[5*width 0 0 interlines],...
   'HorizontalAlignment','left','Callback','ms_updatelabel(2)',...
   'BackgroundColor',white,'Visible','off');

%========= Calculate Projections ==================
%pos=pos-oneline;
h{20}=uicontrol('Parent',fig,'Style','pushbutton','String','Calculate Projections',...
   'Callback','ms_calc_proj;',...
   'Position',pos+[6*width 0 width 0],'Visible','off'); 

%========= Slice plane/Display  ==================
pos=pos-1.5*oneline;

h{21}=uicontrol('Parent',fig,'Style','text','String','Display',...
   	'Position',pos,'BackgroundColor',white,'Visible','off');

%========= Slice/Display vx_min, vx_max, bin_vx ==================
pos=pos-oneline;

h{22}=uicontrol('Parent',fig,'Style','text','String','horizontal range* ',...
		'Tag','ms_disp_x_axis',...
   	'Position',pos+[width 0 width 0],'Visible','off');
h{23}=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_vx_min',...
  	 	'Position',pos+[3*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{24}=uicontrol('Parent',fig,'Style','text','String','to *',...
   	'Position',pos+[4*width 0 0 0],'Visible','off');
h{25}=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_vx_max',...
   	'Position',pos+[5*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');

%========= Slice/Display vy_min, vy_max, bin_vy ==================
pos=pos-oneline;

h{26}=uicontrol('Parent',fig,'Style','text','String','vertical range* ',...
  		'Tag','ms_disp_y_axis',...
   	'Position',pos+[width 0 width 0],'Visible','off');
h{27}=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_vy_min',...
   	'Position',pos+[3*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{28}=uicontrol('Parent',fig,'Style','text','String','to *',...
   	'Position',pos+[4*width 0 0 0],'Visible','off');
h{29}=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_vy_max',...
   	'Position',pos+[5*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');

   
%========= Slice/Display Intensity range ==================
pos=pos-oneline;

h{30}=uicontrol('Parent',fig,'Style','text','String','Intensity range*',...
   	'Position',pos+[width 0 width 0],'Visible','off');
h{31}=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_i_min',...
   	'Position',pos+[3*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{32}=uicontrol('Parent',fig,'Style','text','String','to *',...
   	'Position',pos+[4*width 0 0 0],'Visible','off');
h{33}=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_i_max',...
   	'Position',pos+[5*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{34}=uicontrol('Parent',fig,'Style','text','String','Colour map',...
   	'Position',pos+[6*width 0 0 0],'Visible','off');

h{35}=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_disp_colmap',...
   	'Position',pos+[7*width -interlines 0 interlines],...
   	'HorizontalAlignment','left',...
   	'String',{'black->red','log10(blk-red)','blue->red'},...
   	'BackgroundColor',white,'Value',1,'UserData',coltab,'Visible','off');

   
%========= Slice/Display Smooth Level and Shading ==================
pos=pos-oneline;
h{36}=uicontrol('Parent',fig,'Style','text','String','Smoothing level*',...
   'Position',pos+[width 0 width 0],'Visible','off');

h{37}=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_nsmooth',...
   	'Position',pos+[3*width 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,'Visible','off');
h{38}=uicontrol('Parent',fig,'Style','text','String','Shading',...
   	'Position',pos+[4*width 0 0 0],'Visible','off');
h{39}=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_disp_shad',...
   	'Position',pos+[5*width -interlines 0 interlines],...
   	'HorizontalAlignment','left',...
   	'String',{'flat','faceted'},...
      'BackgroundColor',white,'Value',1,'Visible','off');


%========= Do Slice and Do Surf Slice / Do Display ==================
%pos=pos-oneline;

h{40}=uicontrol('Parent',fig,'Style','pushbutton','String','Display',...
   	'Callback','ms_disp;',...
   	'Position',pos+[6*width 0 0 0],'Visible','off');    


%========= Cut  ==================
pos=pos-1.5*oneline;
h{41}=uicontrol('Parent',fig,'Style','text','String','Cut',...
   'Position',pos,'BackgroundColor',white,'Visible','off');

%========= Cut axis, vx_min, vx_max ==================
pos=pos-oneline;
h{42}=uicontrol('Parent',fig,'Style','text','String',' along axis ',...
   'Position',pos,'Visible','off');

h{43}=uicontrol('Parent',fig,'Style','popupmenu','String',{'u1','u2'},...
	   'Tag','ms_cut_x',...
  		'Position',pos+[width 0 width*1/4 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,...
      'Callback','ms_cut_axes;','Visible','off');

h{44}=uicontrol('Parent',fig,'Style','text','String','from',...
   'Position',pos+[2*width+width*1/4 0 -width*1/4 0],'Visible','off');
h{45}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_cut_vx_min',...
   'Position',pos+[3*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{46}=uicontrol('Parent',fig,'Style','text','String','to',...
   'Position',pos+[4*width 0 0 0],'Visible','off');
h{47}=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_cut_vx_max',...
   'Position',pos+[5*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{48}=uicontrol('Parent',fig,'Style','text','String','step',...
   'Position',pos+[6*width 0 0 0],'Visible','off');
h{49}=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_bin_vx',...
   'Position',pos+[7*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');

%========= Cut vy_min, vy_max ==================
pos=pos-oneline;
h{50}=uicontrol('Parent',fig,'Style','text','String','thickness range',...
	'Tag','ms_cut_y_axis',...
   'Position',pos+[width 0 width 0],'Visible','off');
h{51}=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_vy_min',...
   'Position',pos+[3*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{52}=uicontrol('Parent',fig,'Style','text','String','to',...
   'Position',pos+[4*width 0 0 0],'Visible','off');
h{53}=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_vy_max',...
   'Position',pos+[5*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');

%========= Cut vz_min, vz_max ==================

h{54}=uicontrol('Parent',fig,'Style','text','String','Symbol',...
  	'Position',pos+[6*width 0 0 0],'Visible','off');
h{55}=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_symbol_colour',...
  	'Position',pos+[7*width 0 0 interlines],...
  	'String',{'white','red','blue','magenta','green','cyan','yellow','black'},...
  	'BackgroundColor',white,'Visible','off');

%========= Cut Intensity range and Data Symbol ==================
pos=pos-oneline;

   strings={'Intensity','Q_x','Q_y','Q_z','H','K','L','u1','u2','Energy','|Q|','2Theta','Azimuth','Det Group Number'};

h{56}=uicontrol('Parent',fig,'Style','popupmenu','String',strings,...
   'Value',1,'BackgroundColor',white,'Tag','ms_cut_intensity',...
   'Position',pos+[width 0 width*1/4 interlines],'Visible','off');
h{57}=uicontrol('Parent',fig,'Style','text','String','range*',...
   'Position',pos+[(2+1/4')*width 0 -width*1/4 0]);
h{58}=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_i_min',...
   'Position',pos+[3*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{59}=uicontrol('Parent',fig,'Style','text','String','to *',...
   'Position',pos+[4*width 0 0 0],'Visible','off');
h{60}=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_i_max',...
   'Position',pos+[5*width 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'Visible','off');
h{61}=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_symbol_type',...
   'Position',pos+[6*width 0 0 interlines],...
   'String',{'circle o','square','diamond','pentagram','hexagram','star *','cross x','plus +',...
   'triangle u','triangle d','triangle r','triangle l','point .'},...
	'BackgroundColor',white,'Visible','off');
h{62}=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_symbol_line',...
   'Position',pos+[7*width 0 0 interlines],...
   'String',{'no line','solid -','dashed --','dotted ..','dash-dot _.'},...
   'BackgroundColor',white,'Visible','off');

det_nonpsd_cut= graph_objects_collection(this_name); 
add(mslice_gui,add_handles(det_nonpsd_cut,h));  