function plot_MApow
% function plot_MApow
%
% produces a 'sliceomatic' plot of the Multiresolution data 
% with a colour_axis, by default, with the range; [min(intensity(:)) max(intensity(:))]
%-----------------------------------------------------------
% Ibon Bustinduy [started in 01-November-2005]
%-----------------------------------------------------------
%
%______________________________________________________________________________________________
% More Info: 
% I. Bustinduy, F.J. Bermejo, T.G. Perring, G. Bordel
% A multiresolution data visualization tool for applications in neutron time-of-flight spectroscopy
% Nuclear Inst. and Methods in Physics Research, A. 546 (2005)  498-508.
%
% Author information: Ibon Bustinduy [multiresolution@gmail.com] 
%                URL: http://gtts.ehu.es:8080/Ibon/ISIS/multires.htm 
%
%_______________________________________________________________________________________________
% This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike License. 
% To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/2.0/ 
% or send a letter to Creative Commons, 559 Nathan Abbott Way, Stanford, California 94305, USA.
%_______________________________________________________________________________________________



%by default:
NLEVEL=1;
NERROR=1;

h_ma=findobj('Tag','plot_MApow');
if isempty(h_ma),
   disp('''plot_MApow'' window not active: type ms_MA3d first.');
   return;
end

MApow_d=get(h_ma,'UserData');

 
% fig=findobj('Tag','ms_ControlWindow');
% if isempty(fig),
%    disp('Control Window not active: Open Mslice first.');
%    return;
% end
%h=findobj(fig,'tag','ms_slice_data');
%MA_d=get(h,'UserData');

%-----------------------------------------------------------
 
% === return if slice_d is empty
if isempty(MApow_d),
   disp('## MApow_d contains no data. Plot not performed.');
   return;
end
 



fig=findobj('Tag','plot_MApow');
if isempty(fig),
   colordef none;
   fig=figure('Tag','plot_MApow','PaperPositionMode','auto','Name',':: MULTIRESOLUTION 3D ::','Renderer','zbuffer',...
       'Position',[560    395   450   200]);
   
   % === find any old plot slice figure and set current figure size to match 
   % === the dimensions of the last old figure of the same type
   oldfig=findobj('Tag','old_plot_MApow'); 
   if ~isempty(oldfig),
      oldfig=sort(oldfig);
      set(fig,'Position',get(oldfig(length(oldfig)),'Position'));
   end
else
        figure(fig); 
        clf;
end
 

%--------------------------------------------------------------------------
%++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


%%%%% FRAME for the ERR/S controls...
ft_dir = uicontrol(gcf,...
'Style','frame',...
'BackgroundColor',[0.5,0.5,0.5],...
'Units','normalized','Position',[0.01 0.01 0.98 0.98]);
%%%%% FRAME for the x y controls...
ft_dir = uicontrol(gcf,...
'Style','frame',...
'BackgroundColor',[0.8,0.8,0.8],...
'Units','normalized','Position',[0.02 0.02 0.96 0.96]);

% %%%%% FRAME for the OTHER controls...

% ft_dir = uicontrol(gcf,...
% 'Style','frame',...
% 'BackgroundColor',[0.1,0.1,0.1],...
% 'Units','normalized','Position',[0.76 0.01 0.15 0.98]);





%========= Calculate Projections ==================


%%%%% LABEL for the ERR/S controls...
ERR_label = uicontrol(gcf,...
'Style','text',...
'BackgroundColor','yellow',...
'FontSize',8,'FontName','Arial',...
'String','ERR/S',...
'Tag','ERR_label',...
'Units','normalized','Position',[0.032 0.03 0.07 0.21]);

%%%%% TEXT EDITOR for the ERR/S controls...
ERR_te = uicontrol(gcf,...
'Style','edit',...
'BackgroundColor','yellow',...
'FontSize',8,'FontName','Arial',...
'String',NERROR,...
'Tag','ERR_te',...
'Units','normalized','Position',[0.10 0.03 0.08 0.21],... 
'CallBack','micall_MApow(gcf,''ERR_te'')');

%%%%% SLIDER for the ERR/S 
ERR_slider = uicontrol(gcf,'Style','slider','Units','normalized','Position',[0.22 0.03 0.16 0.21],...
'Min',0,'Max',9e9,'Value',NERROR,...
'Tag','ERR_slider',...
'CallBack','micall_MApow(gcf,''ERR_slider'')');


%%%%% LABEL for the NLEVEL controls...
NLEVEL_label = uicontrol(gcf,...
'Style','text',...
'BackgroundColor','red',...
'FontSize',8,'FontName','Arial',...
'String','NLEVEL',...
'Tag','NLEVEL_label',...
'Units','normalized','Position',[0.42 0.03 0.08 0.21]);

%%%%% TEXT EDITOR for the NLEVEL controls...
NLEVEL_te = uicontrol(gcf,...
'Style','edit',...
'BackgroundColor','red',...
'FontSize',8,'FontName','Arial',...
'String',NLEVEL,...
'Tag','NLEVEL_te',...
'Units','normalized','Position',[0.50 0.03 0.08 0.21],...
'CallBack',...
'micall_MApow(gcf,''NLEVEL_te'')');

%%%%% SLIDER for the NLEVEL 
NLEVEL_slider = uicontrol(gcf,'Style','slider','Units','normalized','Position',[0.58 0.03 0.16 0.21],...
'Min',1,'Max',11,'Value',NLEVEL,'SliderStep',[0.1,0.2],...
'Tag','NLEVEL_slider',...
'CallBack','micall_MApow(gcf,''NLEVEL_slider'')');

%%%%% GO BUTTON 
h=uicontrol('Parent',fig,'Style','pushbutton','String','GO',...
   'Callback','msmapow',...
   'Units','normalized','Position',[0.92 0.03 0.05 0.21]); 

%--------------------------------------------------------------------------
%++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
%--------------------------------------------------------------------------
%++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

% vx_min=MApow_d.slice(1);
% vx_max=MApow_d.slice(2);
% bin_vx_min=MApow_d.slice(3);
% vy_min=MApow_d.slice(4);
% vy_max=MApow_d.slice(5);
% bin_vy_min=MApow_d.slice(6);
bin_vx_min=1;
bin_vy_min=1;


    
%========= Slice/Display vx_min, vx_max, bin_vx ==================
   h=uicontrol('Parent',fig,'Style','text','String','x = Energy',...
		'Tag','MA_x_axis',...
   	    'Units','normalized','Position',[0.03 0.7580 0.17 0.21]);

% 	h=uicontrol('Parent',fig,'Style','edit','Tag','MA_vx_min',...
%   	 	'Units','normalized','Position',[0.10 0.7580 0.08 0.21],...
%         'String',vx_min,...
%    	    'HorizontalAlignment','left',...
%    	    'BackGroundColor',[1,1,1]);
% 
% 	h=uicontrol('Parent',fig,'Style','text','String','to',...
%    	    'Units','normalized','Position',[0.22 0.7580 0.08 0.21]);
% 
% 	h=uicontrol('Parent',fig,'Style','edit','Tag','MA_vx_max',...
%    	    'Units','normalized','Position',[0.30 0.7580 0.08 0.21],...
%    	    'String',vx_max,...
%         'HorizontalAlignment','left',...
%    	    'BackGroundColor',[1,1,1]);

	h=uicontrol('Parent',fig,'Style','text','String','from dx=',...
   	    'Units','normalized','Position',[0.42 0.7580 0.08 0.21]);

	MA_bin_vx=uicontrol('Parent',fig,'Style','text','Tag','MA_bin_vx',...
   	    'Units','normalized','Position',[0.50 0.7580 0.08 0.21],...
   	    'String',bin_vx_min,...
        'HorizontalAlignment','left',...
   	    'BackgroundColor',[1,1,1]);

    h=uicontrol('Parent',fig,'Style','text','String','up to Dx=',...
        'Tag','MA_bin_vx_maxlabel',...
   	    'Units','normalized','Position',[0.58 0.7580 0.08 0.21],'BackgroundColor',[0.8,0.8,0.8]);
    
    MA_bin_vx_max=uicontrol('Parent',fig,'Style','text','String','up to..',...
        'Tag','MA_bin_vx_max',...
   	    'Units','normalized','Position',[0.66 0.7580 0.08 0.21],'BackgroundColor',[1,1,1],'ForeGroundColor',[1,0,0]);
    h=uicontrol('Parent',fig,'Style','text','String','dx = Dx?',...
        'Tag','MA_fix_xlabel',...
   	    'Units','normalized','Position',[0.8 0.7580 0.08 0.21],'BackgroundColor',[0.8,0.8,0.8]);
    MA_fix_x=uicontrol('Parent',fig,'Style','checkbox',...
        'Tag','MA_fix_x','value',false,...
   	    'Units','normalized','Position',[0.88 0.7580 0.03 0.21],'BackgroundColor',[1,1,1],'ForeGroundColor',[1,0,0],...
        'CallBack','micall_MApow(gcf,''MA_fix_x'')');
    
%========= Slice/Display vy_min, vy_max, bin_vy ==================
% PDS detectors
	h=uicontrol('Parent',fig,'Style','text','String','y = Detector',...
  	'Tag','MA_y_axis',...
   	'Units','normalized','Position',[0.03 0.5160 0.17 0.21]);

% 	h=uicontrol('Parent',fig,'Style','text','Tag','MA_vy_min',...
%    	'Units','normalized','Position',[0.10 0.5160 0.08 0.21],...
%     'String',vy_min,...
%    	'HorizontalAlignment','left',...
%    	'BackgroundColor',[1,1,1]);
% 
%     h=uicontrol('Parent',fig,'Style','text','String','to',...
%    	'Units','normalized','Position',[0.22 0.5160 0.08 0.21]);
% 
% 	h=uicontrol('Parent',fig,'Style','edit','Tag','MA_vy_max',...
%    	'Units','normalized','Position',[0.30 0.5160 0.08 0.21],...
%     'String',vy_max,...
%     'HorizontalAlignment','left',...
%    	'BackgroundColor',[1,1,1]);

	h=uicontrol('Parent',fig,'Style','text','String','from dy=',...
   	'Units','normalized','Position',[0.42 0.5160 0.08 0.21]);

	MA_bin_vy=uicontrol('Parent',fig,'Style','text','Tag','MA_bin_vy',...
   	'Units','normalized','Position',[0.50 0.5160 0.08 0.21],...
    'String',bin_vy_min,...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',[1,1,1]);

	h=uicontrol('Parent',fig,'Style','text','String','up to Dy=',...
    'Tag','MA_bin_vy_maxlabel',...
    'Units','normalized','Position',[0.58 0.5160 0.08 0.21],'BackgroundColor',[0.8,0.8,0.8]);

	MA_bin_vy_max=uicontrol('Parent',fig,'Style','text','String','up to',...
    'Tag','MA_bin_vy_max',...
    'Units','normalized','Position',[0.66 0.5160 0.08 0.21],'BackgroundColor',[1,1,1],'ForeGroundColor',[1,0,0]);

    h=uicontrol('Parent',fig,'Style','text','String','dy = Dy?',...
        'Tag','MA_fix_ylabel',...
   	    'Units','normalized','Position',[0.8 0.5160 0.08 0.21],'BackgroundColor',[0.8,0.8,0.8]);
    MA_fix_y=uicontrol('Parent',fig,'Style','checkbox',...
        'Tag','MA_fix_y',...
   	    'Units','normalized','Position',[0.88 0.5160 0.03 0.21],'BackgroundColor',[1,1,1],'ForeGroundColor',[1,0,0],...
        'CallBack','micall_MApow(gcf,''MA_fix_y'')');
    
%-------------------------------

nl=str2double(get(NLEVEL_te,'String'));
bin_vx_min=str2double(get(MA_bin_vx,'String'));
bin_vy_min=str2double(get(MA_bin_vy,'String'));


bin_vx=bin_vx_min.*(2.^(nl-1));
bin_vy=bin_vy_min.*(2.^(nl-1));

set(MA_bin_vx_max,'String',bin_vx);
set(MA_bin_vy_max,'String',bin_vy);


ms_updatelabel_MApow


%--------------------------------------------------------------------------
%++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
%--------------------------------------------------------------------------
%++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

% % === create menu option to be able to do colour hardcopy printouts   
% h=uimenu(fig,'Label','ColourPrint','Tag','Color_Print','Enable','on');
% uimenu(h,'Label','Phaser560','Callback','ms_printc('' \\NDAIRETON\Phaser560:'');');
% uimenu(h,'Label','Phaser0','Callback','ms_printc('' \\NDAIRETON\Phaser0:'');');
% uimenu(h,'Label','DACColour','Callback','ms_printc('' \\NDAIRETON\DACColour:'');');
% uimenu(h,'Label','CRISPColour','Callback','ms_printc('' \\NDAIRETON\CRISPColour:'');');      
% uimenu(h,'Label','MAPSColour','Callback','ms_printc('' \\NDAIRETON\MAPSColour:'');');      
% uimenu(h,'Label','R3-COL00','Callback','ms_printc('' \\ndablagrave\R3-COL00'');'); 
% %=== TO ADD ANOTHER POSTSCRIPT PRINTER IN THIS LIST INSERT ANOTHER LINE AS ABOVE AND 
% %=== EDIT NAME (LABEL) 'Phaser0' AND NETWORK PATH '' \\NDAIRETON\Phaser0:''
% uimenu(h,'Label','default printer','Callback','ms_printc;');   
% % % === create menu option to be able to keep figure
% % h=uimenu(fig,'Label','Keep','Tag','keep','Enable','on');
% % uimenu(h,'Label','Keep figure','Callback','keep(gcf);');
% % % === create menu option to be able to make old slice figures current
% % h=uimenu(fig,'Label','Make Current','Tag','make_cur','Enable','off');
% % uimenu(h,'Label','Make Figure Current','Callback','make_cur(gcf);');


%========== Top Menu : About ==========================
hmenu=uimenu(fig,'Label','About Multiresolution powder');
hmenu1=uimenu(hmenu,'Label','__________________________________________________________________');
hmenu1=uimenu(hmenu,'Label',['Multiresolution powder GUI. BETA version']);
hmenu1=uimenu(hmenu,'Label', 'Mslice add-on Software for POWDER Neutron Data');
hmenu1=uimenu(hmenu,'Label', '-written by ibon bustinduy from 2003 to 2005-');
hmenu1=uimenu(hmenu,'Label','__________________________________________________________________');
hmenu1=uimenu(hmenu,'Label','           [Centro Superior de Investigaciones Cientificas, Spain]');
hmenu1=uimenu(hmenu,'Label','           [and ISIS Facility, Rutherford Appleton Laboratory, UK]');
hmenu1=uimenu(hmenu,'Label','           email : multiresolution@gmail.com');
hmenu1=uimenu(hmenu,'Label','           URL   : http://gtts.ehu.es:8080/Ibon/ISIS/multires.htm');
hmenu1=uimenu(hmenu,'Label','__________________________________________________________________');


