function pos = msui_det_hkl_points(fig,pos,oneline,lineoffset,interlines,white)

this_name='det_hkl_points'; 
mslice_gui = msui_collection(fig,'mslice_gui');
if exist(mslice_gui,this_name)
    pos = get_line_pos(get(mslice_gui,this_name));
    return
end

    
h{1}=uicontrol('Parent',fig,'Style','text','String','(hkl) points',...
   	'Position',pos,'Visible','off');
h{2}=uicontrol('Parent',fig,'Style','checkbox',...
   	'Tag','ms_plot_traj_hkl_points',...
   	'HorizontalAlignment','left',...
   	'Position',pos+[pos(3) 0 -3*pos(3)/4 0],...
		'Value',0,'Visible','off');
h{3}=uicontrol('Parent',fig,'Style','text','String','(hkl) labels',...
   	'Position',pos+[1.5*pos(3) 0 0 0],'Visible','off');
h{4}=uicontrol('Parent',fig,'Style','checkbox',...
   	'Tag','ms_plot_traj_hkl_labels',...
   	'HorizontalAlignment','left',...
   	'Position',pos+[2.5*pos(3) 0 -3*pos(3)/4 0],...
		'Value',0,'Visible','off');

 det_hkl_points= graph_objects_collection(this_name); 
 add(mslice_gui,add_handles(det_hkl_points,h));  
