function  msui_powder_menu(h_root,position,white,analmode,sample)
%
% remove the part of ui responsible for crystal analysis
mslice_gui = get(findobj('Tag','mslice_gui'),'UserData'); 
mslice_gui = delete(mslice_gui,{'cryst_analysis_psd','cryst_analysis_nonpsd','detector_type_psd'});
if sample==2
    delete(mslice_gui,{'single_crystal_gui'});
end

width      = position(3);
height      = position(4);
oneline    = [0,height,0,0];
interlines = 0;

pos    =position-1.5*oneline;
% build select axis block
pos=ui_select_axis(h_root,pos,white);

%build slice block
% LOAD COLOR TAB
global coltab;
if isempty(coltab)
    load coltab.dat -ascii;
end
pos(3) = width;
pos     = ui_powder_slice(pos,h_root,oneline,interlines,white,coltab);

% build cut block;
pos =ui_powder_cut(pos,h_root,oneline,interlines,white,sample);

% cut output block -- the same for crystall and powder mode, so does its
% own existance check;
pos(2)  = pos(2)-0.1*height;
msui_cut_output(pos,h_root,oneline,interlines,white,sample);

if (analmode == 2)  % powder;
     delete(mslice_gui,'delta_phi_range');
end
 
if (analmode == 3)  % powder remap;
    % if it has been created above, mslice_gui knows nothing about it here; need to retrieve it from fig singleton; 
    axis_selection =get(msui_collection(h_root,'mslice_gui'),'powder_axis'); 
    r_max = axis_selection.r_max;
    position(1) = pos(1) + 3*width;
    position(2) = r_max(2)-height;

    msui_delta_phi_range(h_root,position, white);
end

% 
function pos     = ui_select_axis(h_root,pos,white)

this_name = 'powder_axis';
mslice_gui = get(findobj('Tag','mslice_gui'),'UserData');
if exist(mslice_gui,this_name)
     pos = get_line_pos(get(mslice_gui,this_name)); 
    return;
end

width = pos(3);
%========= Viewing Axes + Label ==================
axis_cel = graph_objects_collection(this_name,...
                                    uicontrol('Parent',h_root,'Style','text','String','Viewing Axes',...
                                    'Position',pos,'BackgroundColor',white,'Visible','off'));
axis_cel =add_right(axis_cel ,...
                                    uicontrol('Parent',h_root,'Style','text','String','Selection',...
                                     'Visible','off'));                                                       
axis_cel=add_right(axis_cel ,...
                                    uicontrol('Parent',h_root,'Style','text','String','Label',...
                                     'BackgroundColor',white,'Position',pos+[0,0,width,0],'Visible','off'));                                                        
%========= u1  ==================
strings={'Energy','|Q|','2Theta','Azimuth','Det Group Number'};
%
u1_row =graph_objects_collection('u1_row',...,
                 uicontrol('Parent',h_root,'Style','text','String','u1','Position',pos,'Visible','off'));
grey = get(u1_row.handles{1},'BackgroundColor');

u1_row =add_right(u1_row,...
                 uicontrol('Parent',h_root,'Style','popupmenu','Tag','ms_u1',...
                              'HorizontalAlignment','left',...
                              'BackgroundColor',white,'String',strings,'Value',2,...
                              'Callback','ms_updatelabelu(1);','Visible','off')); 
u1_row =add_right(u1_row,...                          
                uicontrol('Parent',h_root,'Style','edit','Enable','on','Tag','ms_u1label',...
                               'HorizontalAlignment','left','Callback','ms_updatelabel(1)',...
                              'BackgroundColor',white,'Position',pos+[0,0,width,0],'String','u1','Visible','off'));    
axis_cel= add_collection(axis_cel,u1_row,[0,-1]);

%========= u2  ==================
u2_row =graph_objects_collection('u2_row',...,
               uicontrol('Parent',h_root,'Style','text','String','u2','Position',pos,'Visible','off'));
u2_row =add_right(u2_row,...
              uicontrol('Parent',h_root,'Style','popupmenu','Tag','ms_u2',...
                             'HorizontalAlignment','left',...
                            'BackgroundColor',white,'String',strings,'Value',1,...
                         	'Callback','ms_updatelabelu(2);','Visible','off'));
u2_row =add_right(u2_row,...
             uicontrol('Parent',h_root,'Style','edit','Enable','on','Tag','ms_u2label',...
                           'HorizontalAlignment','left','Callback','ms_updatelabel(2)',...
                          'BackgroundColor',white,'Position',pos+[0,0,width,0],'String','u2','Visible','off'));
axis_cel= add_collection(axis_cel,u2_row,[0,-1]);

col_width = [width,width,0.7*width];
axis_cel=set_width(axis_cel,col_width);
height = pos(4);
axis_cel=add_bottom(axis_cel,...
              uicontrol('Parent',h_root,'Style','frame','Position',[0,0,sum(col_width),0.4*height],...
             'ForegroundColor',grey,'Visible','off'));

%========= Calculate Projections ==================
r_min = axis_cel.r_min;
r0       = [r_min(1)+6*width,r_min(2)];
pos(1:2)=r0;
pos(3)   =2*width;

h=uicontrol('Parent',h_root,'Style','pushbutton','String','Calculate Projections',...
   'Callback','ms_calc_proj;',...
   'Position',pos,'Visible','off'); 
axis_cel= add_handles(axis_cel,h);


% add the handles to the collection and add it to the mslice_gui;
add(mslice_gui,axis_cel);       
pos(1:2) = axis_cel.r_min;

%
function pos = ui_powder_slice(pos,h_root,oneline,interlines,white,coltab)

this_name = 'powder_slice';
mslice_gui = get(findobj('Tag','mslice_gui'),'UserData');
if exist(mslice_gui,this_name)
     pos = get_line_pos(get(mslice_gui,this_name)); 
    return;
end


width = pos(3);
height= pos(4);
pos(2)=pos(2)-height;

hb = cell(20,1);
%========= Slice plane/Display  ==================
hb{1}=uicontrol('Parent',h_root,'Style','text','String','Display',...
    'Position',pos,'BackgroundColor',white,'Visible','off');

%========= Display vx_min, vx_max, bin_vx ==================
%
pos(3)=width;

pos=pos-oneline;
hb{2}=uicontrol('Parent',h_root,'Style','text','String','horizontal range ',...
	'Tag','ms_disp_x_axis',...
  	'Position',pos+[pos(3) 0 pos(3) 0],'Visible','off');
hb{3}=uicontrol('Parent',h_root,'Style','edit','Tag','ms_disp_vx_min',...
 	'Position',pos+[3*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white,'Visible','off');
hb{4}=uicontrol('Parent',h_root,'Style','text','String','to *',...
  	'Position',pos+[4*pos(3) 0 0 0],'Visible','off');
hb{5}=uicontrol('Parent',h_root,'Style','edit','Tag','ms_disp_vx_max',...
  	'Position',pos+[5*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white,'Visible','off');

%========= Display vy_min, vy_max, bin_vy ==================
pos=pos-oneline;
hb{6}=uicontrol('Parent',h_root,'Style','text','String','vertical range',...
	'Tag','ms_disp_y_axis',...
  	'Position',pos+[pos(3) 0 pos(3) 0],'Visible','off');
hb{7}=uicontrol('Parent',h_root,'Style','edit','Tag','ms_disp_vy_min',...
  	'Position',pos+[3*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white,'Visible','off');
hb{8}=uicontrol('Parent',h_root,'Style','text','String','to *',...
  	'Position',pos+[4*pos(3) 0 0 0],'Visible','off');
hb{9}=uicontrol('Parent',h_root,'Style','edit','Tag','ms_disp_vy_max',...
  	'Position',pos+[5*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white,'Visible','off');
   
%========= Display Intensity range ==================
pos=pos-oneline;
hb{10}=uicontrol('Parent',h_root,'Style','text','String','Intensity range*',...
  	'Position',pos+[pos(3) 0 pos(3) 0],'Visible','off');
hb{11}=uicontrol('Parent',h_root,'Style','edit','Tag','ms_disp_i_min',...
  	'Position',pos+[3*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white,'Visible','off');
hb{12}=uicontrol('Parent',h_root,'Style','text','String','to *',...
  	'Position',pos+[4*pos(3) 0 0 0],'Visible','off');
hb{13}=uicontrol('Parent',h_root,'Style','edit','Tag','ms_disp_i_max',...
  	'Position',pos+[5*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white,'Visible','off');
hb{14}=uicontrol('Parent',h_root,'Style','text','String','Colour map',...
  	'Position',pos+[6*pos(3) 0 0 0],'Visible','off');

hb{15}=uicontrol('Parent',h_root,'Style','popupmenu','Tag','ms_disp_colmap',...
  	'Position',pos+[7*pos(3) -interlines 0 interlines],...
  	'HorizontalAlignment','left',...
  	'String',{'black->red','log10(blk-red)','blue->red'},...
  	'BackgroundColor',white,'Value',1,'UserData',coltab,'Visible','off');

   
%========= Display Smooth Level and Shading ==================
pos=pos-oneline;
hb{16}=uicontrol('Parent',h_root,'Style','text','String','Smoothing level*',...
   'Position',pos+[pos(3) 0 pos(3) 0],'Visible','off');
hb{17}=uicontrol('Parent',h_root,'Style','edit','Tag','ms_disp_nsmooth',...
  	'Position',pos+[3*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white,'Visible','off');
hb{18}=uicontrol('Parent',h_root,'Style','text','String','Shading',...
  	'Position',pos+[4*pos(3) 0 0 0],'Visible','off');
hb{19}=uicontrol('Parent',h_root,'Style','popupmenu','Tag','ms_disp_shad',...
  	'Position',pos+[5*pos(3) -interlines 0 interlines],...
  	'HorizontalAlignment','left',...
  	'String',{'flat','faceted'},...
   'BackgroundColor',white,'Value',1,'Visible','off');
%=============================================

%========= Do Display ==================
%pos=pos-oneline;
hb{20}=uicontrol('Parent',h_root,'Style','pushbutton','String','Display',...
  	'Callback','ms_disp;',...
  	'Position',pos+[6*pos(3) 0 width 0],'Visible','off');    
                             
% create graphic elements colllection
powder_slice =graph_objects_collection(this_name);
% add the handles to the collection and add it to the mslice_gui;
add(mslice_gui,add_handles(powder_slice,hb));
%
function pos =ui_powder_cut(pos,h_root,oneline,interlines,white,sample)

this_name = 'powder_cut';
mslice_gui = get(findobj('Tag','mslice_gui'),'UserData');
if exist(mslice_gui,this_name)
     pos = get_line_pos(get(mslice_gui,this_name)); 
    return;
end

hc=cell(10,1);
width = pos(3);
height= pos(4);
%========= Cut  ==================
pos(2)=pos(2)-height;
hc{1}=uicontrol('Parent',h_root,'Style','text','String','Cut',...
                      'Position',pos,'BackgroundColor',white,'Visible','off');

%========= Cut axis, vx_min, vx_max ==================
pos=pos-oneline;
hc{2}=uicontrol('Parent',h_root,'Style','text','String',' along axis ',...
                      'Position',pos,'Visible','off');
%
%
pos(3)=width;

hc{3}=uicontrol('Parent',h_root,'Style','popupmenu','String',{'u1','u2'},...
                      'Tag','ms_cut_x',...
                      'Position',pos+[pos(3) 0 pos(3)*1/4 interlines],...
                      'HorizontalAlignment','left',...
                      'BackgroundColor',white,...
                      'Callback','ms_cut_axes;','Visible','off');
hc{5}=uicontrol('Parent',h_root,'Style','text','String','from',...
                      'Position',pos+[2*pos(3)+pos(3)*1/4 0 -pos(3)*1/4 0],'Visible','off');
hc{6}=uicontrol('Parent',h_root,'Style','edit','Enable','on','Tag','ms_cut_vx_min',...
                     'Position',pos+[3*pos(3) 0 0 interlines],...
                     'HorizontalAlignment','left',...
                     'BackgroundColor',white,'Visible','off');
hc{7}=uicontrol('Parent',h_root,'Style','text','String','to',...
                       'Position',pos+[4*pos(3) 0 0 0],'Visible','off');
hc{8}=uicontrol('Parent',h_root,'Style','edit','Enable','on','Tag','ms_cut_vx_max',...
                      'Position',pos+[5*pos(3) 0 0 interlines],...
                      'HorizontalAlignment','left',...
                      'BackgroundColor',white,'Visible','off');
hc{9}=uicontrol('Parent',h_root,'Style','text','String','step',...
                        'Position',pos+[6*pos(3) 0 0 0],'Visible','off');
hc{10}=uicontrol('Parent',h_root,'Style','edit','Tag','ms_cut_bin_vx',...
                       'Position',pos+[7*pos(3) 0 0 interlines],...
                       'HorizontalAlignment','left',...
                        'BackgroundColor',white,'Visible','off');

%========= Cut vy_min, vy_max ==================
pos=pos-oneline;
hc{11}=uicontrol('Parent',h_root,'Style','text','String','thickness range',...
                    	'Tag','ms_cut_y_axis',...
                        'Position',pos+[pos(3) 0 pos(3) 0],'Visible','off');
hc{12}=uicontrol('Parent',h_root,'Style','edit','Tag','ms_cut_vy_min',...
                       'Position',pos+[3*pos(3) 0 0 interlines],...
                       'HorizontalAlignment','left',...
                       'BackgroundColor',white,'Visible','off');
hc{13}=uicontrol('Parent',h_root,'Style','text','String','to',...
                      'Position',pos+[4*pos(3) 0 0 0],'Visible','off');
hc{14}=uicontrol('Parent',h_root,'Style','edit','Tag','ms_cut_vy_max',...
                      'Position',pos+[5*pos(3) 0 0 interlines],...
                      'HorizontalAlignment','left',...
                      'BackgroundColor',white,'Visible','off');
hc{15}=uicontrol('Parent',h_root,'Style','text','String','Symbol',...
                      'Position',pos+[6*pos(3) 0 0 0],'Visible','off');
hc{16}=uicontrol('Parent',h_root,'Style','popupmenu','Tag','ms_cut_symbol_colour',...
                       'Position',pos+[7*pos(3) 0 0 interlines],...
                       'String',{'white','red','blue','magenta','green','cyan','yellow','black'},...
                       'BackgroundColor',white,'Visible','off');

%========= Cut Intensity range and Data Symbol ==================
pos=pos-oneline;
strings={'Intensity','Energy','|Q|','2Theta','Azimuth','Det Group Number'};
if (sample==1),	% single crystal sample anlysed as powder
   strings={'Intensity','Q_x','Q_y','Q_z','H','K','L','Energy','|Q|','2Theta','Azimuth','Det Group Number'};
end
hc{17}=uicontrol('Parent',h_root,'Style','popupmenu','String',strings,...
                        'Value',1,'BackgroundColor',white,'Tag','ms_cut_intensity',...
                        'Position',pos+[pos(3) 0 pos(3)*1/4 interlines],'Visible','off');
hc{18}=uicontrol('Parent',h_root,'Style','text','String','range*',...
                        'Position',pos+[(2+1/4)*pos(3) 0 -pos(3)*1/4 0],'Visible','off');
hc{19}=uicontrol('Parent',h_root,'Style','edit','Tag','ms_cut_i_min',...
                        'Position',pos+[3*pos(3) 0 0 interlines],...
                        'HorizontalAlignment','left',...
                        'BackgroundColor',white,'Visible','off');
hc{20}=uicontrol('Parent',h_root,'Style','text','String','to *',...
                         'Position',pos+[4*pos(3) 0 0 0],'Visible','off');
hc{21}=uicontrol('Parent',h_root,'Style','edit','Tag','ms_cut_i_max',...
                         'Position',pos+[5*pos(3) 0 0 interlines],...
                         'HorizontalAlignment','left',...
                         'BackgroundColor',white,'Visible','off');
hc{22}=uicontrol('Parent',h_root,'Style','popupmenu','Tag','ms_cut_symbol_type',...
                        'Position',pos+[6*pos(3) 0 0 interlines],...
                        'String',{'circle o','square','diamond','pentagram','hexagram','star *','cross x','plus +',...
                        'triangle u','triangle d','triangle r','triangle l','point .'},...
                        'BackgroundColor',white,'Visible','off');
hc{23}=uicontrol('Parent',h_root,'Style','popupmenu','Tag','ms_cut_symbol_line',...
                        'Position',pos+[7*pos(3) 0 0 interlines],...
                       'String',{'no line','solid -','dashed --','dotted ..','dash-dot _.'},...
                       'BackgroundColor',white,'Visible','off');



 % create graphic elements colllection
powder_slice =graph_objects_collection(this_name);
% add the handles to the collection and add it to the mslice_gui;
add(mslice_gui,add_handles(powder_slice,hc));
