function rez=spe_hdf_filestructure(field_name)
% this private function describes the structure of spe-hdf file version 2
% it may change if versions increases
% Usage:
%>>rez=spe_hdf_filestructure()  -- returns the structure, which describes
%                                  the spe_hdf5 file structure on hdd
%>>rez=spe_hdf_filestructure(field_name)
%                               -- returns the default value of the correspondent
%                                  spe_hdf5 structure if the field name
%                                  exist and error othewise
% WARNING !!!  All modified fields which may be needed for new modified file formats
%              should be added to the end of existing file structure as users of the filestructure may refer exsisting structure fields by
%              their numbers (BAD!!!).
%
% $Revision$ ($Date$)
%

file_structure=struct(...
    'spe_hdf_version',{2,3},...
    'spe_hdf_file_ext',{'.spe_h5','.nxspe'},...   % what extension to use for spe-hdf files.
    'data_field_names',{[],[]},...
    'data_attrib_names',{[],[]}...
);
% the names of the data fields which are present in a spe hdf5 file
file_structure(1).data_field_names=...
            {'Ei',...    'Ei', 10, ... % input energy identified from homering;
            'En_Bin_Bndrs',...
            'S(Phi,w)',...
            'Err',...
            'spe_hdf_version'};
file_structure(1).data_attrib_names={};
file_structure(2).data_field_names=...
            {'NXSPE_info/fixed_energy',...    
            'data/energy',...
            'data/data',...
            'data/error',...
            'definition',...   % these fields are fixed for compartibility; Others are expected from nxspe file;
            'NXSPE_info/psi',... 
            'data/azimuthal','data/azimuthal_width','data/polar','data/polar_width',...
            };
file_structure(2).data_attrib_names={'units',...
    'units','','','version','units','','','','',...
    };        
if exist('field_name','var')
    if isfield(file_structure,field_name)
        rez={file_structure.(field_name)};
    else
        error('SPE:spe_hdf_filestructure',' requested non-existent field %s',field_name);
    end
else
    rez=file_structure;
end



